# Generated by Django 6.0.6 on 2026-06-28 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog_21', '0002_delete_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название игры')),
                ('reason', models.TextField(help_text='Например: клиенты часто просят', verbose_name='Почему стоит добавить')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрена'), ('added', 'Игра добавлена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, default='', verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_requests', to='catalog_21.platform', verbose_name='Платформа')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто подал заявку')),
            ],
            options={
                'verbose_name': 'Заявка на игру',
                'verbose_name_plural': 'Заявки на игры',
                'ordering': ['-created_at'],
            },
        ),
    ]
