# Generated by Django 6.0.6 on 2026-06-30 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.AddField(
            model_name='tournament',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершён в'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Предстоящий'), ('ACTIVE', 'Активный'), ('FINISHED', 'Завершён')], default='UPCOMING', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_rating', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Рейтинг игрока',
                'verbose_name_plural': 'Рейтинги игроков',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField(verbose_name='Место')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', verbose_name='Турнир')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_results', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Результат турнира',
                'verbose_name_plural': 'Результаты турниров',
                'ordering': ['place'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
