# Generated by Django 6.0.6 on 2026-06-27 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog_21', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(verbose_name='Конец')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('COMPLETED', 'Завершена'), ('CANCELED', 'Отменена')], default='ACTIVE', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий админа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('disc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog_21.disc', verbose_name='Диск с игрой')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog_21.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['-start_time'],
            },
        ),
    ]
