# Generated by Django 6.0.6 on 2026-06-27 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя / Никнейм')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='В черном списке')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки о клиенте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название игры')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Жанр')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название платформы')),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер / Штрихкод')),
                ('condition', models.CharField(default='Отличное', max_length=100, verbose_name='Состояние')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Свободен'), ('IN_USE', 'В игре'), ('BROKEN', 'Сломан/Ремонт'), ('LOST', 'Утерян')], default='AVAILABLE', max_length=20, verbose_name='Статус диска')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_21.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Диск',
                'verbose_name_plural': 'Диски',
                'ordering': ['barcode'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_21.platform', verbose_name='Платформа'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Номер комнаты / Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Комната работает')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_21.platform', verbose_name='Платформа')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['name'],
            },
        ),
    ]
