# Generated by Django 6.0.6 on 2026-06-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_21', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
